[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && python -m spacy download en_core_web_sm"

[deploy]
startCommand = "gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 100

[[ports]]
port = 8000
protocol = "http"
